project:
  type: website
  output-dir: docs

website:
  title: "#blogR"
  site-url: https://rsilveirafh.github.io/blogR/
  description: "%>%ing the World"
  page-footer: 
    left: "Blog made with [Quarto](https://quarto.org/), by Ricardo da Silveira Filho."
  navbar:
    right: 
      - about.qmd
      - icon: github
        href: https://github.com/rsilveirafh
      - icon: envelope
        href: mailto:ricardodasilveira@gmail.com
format:
  html:
    smooth-scroll: true
    theme: 
     light: flatly
     dark: darkly
    css: styles.css
    highlight-style: github



