project:
  type: website
  output-dir: docs

website:
  title: "#blogR"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rsilveirafh
      - icon: envelope
        href: mailto:ricardodasilveira@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: tango



